@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class "<<interface>>\nReadOnlyTAssist" as ReadOnlyTAssist
Class TAssist
Class ModelManager
Class UserPrefs
Class Group
Class Student
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .down.> ReadOnlyTAssist
ModelManager -down-> "1" TAssist
ModelManager -right-> "1" UserPrefs
TAssist .up.|> ReadOnlyTAssist
UserPrefs .up.|> ReadOnlyUserPrefs
TAssist --> "~* all" Group
Group --> "~* all" Student
@enduml
