@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class TAssistParser
Class CommandRegistry
Class XYZCommandParser
Class TAssistArgumentParser
Class TAssistParserUtil
Class ArgumentMultimap
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> TAssistParser

TAssistParser .down.> XYZCommandParser: <<create>>
TAssistParser --> "1" CommandRegistry
CommandRegistry --> "*" Parser

XYZCommandParser ..> XYZCommand : <<create>>
TAssistParser ..> Command : <<use>>
XYZCommandParser .up.|> Parser
XYZCommandParser ..> TAssistArgumentParser
XYZCommandParser ..> TAssistParserUtil
TAssistArgumentParser ..> ArgumentMultimap
ArgumentMultimap ..> Prefix
TAssistArgumentParser ..> Prefix
XYZCommand -up-|> Command
@enduml
