@startuml
!pragma layout smetana
skinparam shadowing false
skinparam packageStyle rectangle
skinparam classBackgroundColor #1D8900
skinparam classFontColor white
skinparam classBorderColor white
skinparam packageBackgroundColor white
hide members
hide circle
skinparam arrowThickness 1.1
skinparam arrowColor #0E4100

package UI <<Rectangle>> {
interface Ui
class UiManager
class MainWindow
class GroupStrip
class WorkspacePanel
class CommandBox
class ResultDisplay
class StatusBarFooter
class StudentListPanel
class FeaturePreview
class HelpPanel
class StoragePanel
}

UiManager .up.|> Ui
UiManager --> MainWindow
MainWindow *--> CommandBox
MainWindow *--> ResultDisplay
MainWindow *--> StatusBarFooter
MainWindow *--> GroupStrip
MainWindow *--> WorkspacePanel
WorkspacePanel *--> StudentListPanel
WorkspacePanel *--> "4" FeaturePreview
WorkspacePanel *--> HelpPanel
WorkspacePanel *--> StoragePanel

note bottom of WorkspacePanel
View components inherit from UiPart.
end note

interface Logic #3333C4
class Group #9D0012
class Student #9D0012
MainWindow --> Logic
MainWindow ..> Group
StudentListPanel ..> Group
GroupStrip ..> Group
StudentListPanel ..> Student
@enduml
